endpoints:
  logfile:
    enabled: true

logging:
  config: classpath:logback.xml
  file:
    path: /log

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:6688/eureka/

spring:
  mail:
    # host: smtp.163.com
    host: smtp.qq.com
    #port: 465
    # username: mortalliaoyujian@163.com
    username: 717563486@qq.com
    #163邮箱密码
    # password:
    #QQ邮箱授权码
    password: mhwgstsizrvybfhc
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
          required: true
